spring:
  application:
    name: movies
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}

#JWT configuration
jwt:
  secret: your-very-secret-key-that-is-long-enough!